[package]
name = "llm-token"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Token counting and handling for LLM messages"

[dependencies]
llm-types = { version = "0.1.0", path = "../llm-types" }
serde_json = { workspace = true }

[dev-dependencies]
llm-common = { version = "0.1.0", path = "../llm-common" }
